import React from "react";

export default (props) => (
  <div>
    <header>Terms & Conditions</header>

    <p>Only the English version of the terms of use is legally binding. Translations have been provided purely for user convenience. In the event of discrepancy between a translation and the English master, the English master prevails.</p>

    <p>Use of Trippur is subject to the terms of use outlined below. Please read the terms of use carefully before using Trippur: By using Trippur you agree to these terms of use.</p>

    <p>This terms of use agreement ("agreement") sets forth the legally binding terms for your use of Trippur Services. By using the Trippur Services, you agree to be bound by this Agreement, whether you are a "Visitor" (which means that you simply browse the Trippur Website), or a "Member" (which means that you have registered with Trippur). The term "User" refers to a Visitor or a Member. You are only authorised to use Trippur Services (regardless of whether your access or use is intended) if you agree to abide by all applicable laws and to this Agreement. If you wish to become a Member, communicate with other Members and make use of Trippur Services, you must read this Agreement and indicate your acceptance during the Registration process. The content and information on this website and mobile applications (including, without limitation, price and availability of travel services), as well as the software and infrastructure used to provide such content and information, is proprietary to Trippur B.V. (“Trippur”) or its affiliates, suppliers, and providers.</p>

    <p>Trippur may modify this agreement from time to time and such modification shall be effective upon posting by Trippur on the Trippur website. You agree to be bound to any changes to this agreement when you use the Trippur services after any such modification is posted. It is therefore important that you review this agreement regularly to ensure you are updated as to any changes.</p>

    <p className="title">Privacy policy</p>
    <p>Your use of this website and future apps is governed by Trippur’s privacy policy, which is available on the Trippur privacy policy page and incorporated by reference into these terms.</p>

    <p className="title">Description of service</p>
    <p>Trippur provides users with tools and resources for searching, planning and sharing travel services, including online collaboration tools and search services now available or hereafter developed, including without limitation any software incorporated into such tools and services (the "service"). Trippur is not a travel agent or merchant. After completing a search on Trippur, you can choose to be transferred to the third-party web- or mobile site of the vendor you have selected, where a booking may be completed. Trippur is not responsible for the terms of use or the privacy policy of the web- or mobile sites where you complete your booking. Trippur strongly recommends that you read the terms of use and privacy policy of the vendor’s web- or mobile sites. Trippur is not responsible for collecting or remitting taxes in connection with your purchases of products and services from these third party travel providers. You understand and agree that the Service is provided "as-is" and that Trippur assumes no responsibility for the timeliness, deletion, service delivery problem, or failure to search, store any user information, user communications or personalization settings. Trippur is a complimentary service for your personal and non-commercial use. You may not access Trippur using automated processes, even if this is for personal use.</p>

    <p className="title">Use of copyrighted materials/trademarks</p>
    <p>Any materials on this website or app, including without limitation any documentation, content, text, data, graphics, images, interfaces or other materials or works of authorship, (the "Materials") are copyrighted materials owned by or licensed to Trippur. All rights are reserved. The Materials contain trademarks, service marks and trade names which are owned by Trippur and its affiliates, and may also contain brand and product names which are trademarks, service marks or trade names of third parties which are owned by their respective owners. Except as otherwise noted in the website or the apps, you are hereby authorized to view, download, cache, copy, and print the Materials, subject to the following conditions: (1) Any copy of the Materials or portion thereof must include the Trippur copyright notice. (2) Trippur reserves the right to revoke such authorization at any time, and any such use by you shall be discontinued immediately upon notice from Trippur.</p>

    <p className="title">Hyperlinks to this website</p>
    <p>You are granted a limited, nonexclusive right to create a "hypertext" link to the home page of this website or app provided that such link does not portray Trippur or any of its other products or services in a false, misleading, derogatory, or otherwise defamatory manner. This limited right may be revoked at any time for any reason whatsoever. You may not use, frame, or utilize framing techniques to enclose any Trippur trademark, logo or trade name or other proprietary information including the images found at the website, the content of any text or the layout/design of any page or any form contained on a page without the express written consent of Trippur.</p>

    <p className="title">Member accounts, passwords and security</p>
    <p>Certain areas of the website or the app may be password-restricted and require registration or sign-in before they can be accessed. When you complete our registration process you will receive a profile and you select your own password that will enable you to access all travel services. You agree to maintain the confidentiality of your password, and are fully responsible for all liability and damages resulting from your failure to maintain that confidentiality and all activities that occur through the use of your password. You agree to immediately notify us of any unauthorised use of your password or any other breach of security. You agree that Trippur cannot and will not be liable for any loss or damage arising from your failure to comply with this policy. When you have logged in to your profile you will remain logged in until you log out even if you close the browser used by you.</p>

    <p className="title">Content submitted for inclusion on or for distribution through Trippur</p>
    <p>You acknowledge that you are responsible for the information, photographs, graphics, messages, content and other material that you upload, post, email or otherwise submit to the website or the app or make available using the service, and that you have full responsibility for each of your submissions, including its legality, reliability, appropriateness, originality, and copyright. Trippur does not claim ownership of content (including photos and graphics) you submit or make available for inclusion as part of our travel content. However, with respect to travel content you submit or make available for inclusion as part of Trippur’s travel content, you grant Trippur a world-wide, royalty free, and non-exclusive license to use, distribute, reproduce, modify, adapt, and publicly display such content for the purposes of providing and promoting the destination to which such content was submitted. This license exists only for as long as you elect to continue to include such content on the service and will terminate at the time you remove or Trippur removes such content from the service. You agree to provide a world-wide, royalty free, non-exclusive, and irrevocable license to use, distribute, reproduce, modify, adapt, publicly display, and sublicense content (including photos and graphics) you submit or make available for inclusion in "publicly accessible" areas of the service. "Publicly accessible" areas of the service are those areas that are intended by Trippur to be available to the general public including travel content where the option to share travel content with the public has been selected. Publicly accessible areas do not include travel content that you have selected to keep as your favourite travel content. Trippur does not control the content posted by third parties via the service and, as such, does not guarantee the accuracy, integrity or quality of such content. You understand that by using the service, you may be exposed to content that is offensive, indecent, or objectionable. Under no circumstances will Trippur be liable in any way for any content, including, but not limited to, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available via the service.</p>

    <p className="title">General practices regarding use of Trippur</p>
    <p>You acknowledge that Trippur may establish general practices and limits concerning use of the service, including without limitation the maximum number of itineraries that may be saved in your profile, the maximum size of members that can work on a specific itinerary and the maximum disk space that will be allotted on Trippur’s servers on your behalf. In addition, you agree not to take any action that might impose, in Trippur 's discretion, a disproportionately large load on Trippur 's servers or infrastructure.</p>

    <p className="title">Modification of service</p>
    <p>Trippur reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently the service (or any part thereof) with or without notice. You agree that Trippur shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the service. Termination You agree that Trippur may, at its sole discretion and without prior notice, immediately terminate your profile and access to the service. Cause for such termination shall include, but not be limited to, (a) breaches or violations of these terms of use or other Trippur agreements or guidelines, (b) requests by law enforcement or other government agencies, (c) a request by you (self-initiated account deletions), (d) discontinuance or material modification to the service (or any part thereof), (e) unexpected technical or security issues or problems, (f) extended periods of inactivity, (g) you have engaged in fraudulent or illegal activities, and/or (h) non-payment of any fees owed by you in connection with the services. Termination of your profile includes (a) removal of access to all offerings within the service, including but not limited to your travel itineraries, (b) deletion of your password and all related information, files, and content associated with or inside your account (or any part thereof), and (c) barring further use of the service. Further, you agree that all terminations for cause shall be made in Trippur 's discretion and that Trippur shall not be liable to you or any third-party for any termination of your profile or access to itineraries created using the service.</p>

    <p className="title">Liability disclaimer</p>
    <p>Your use of the service is at your sole risk. The service is provided on an "as-is" and "as available" basis. Trippur expressly disclaims all warranties of any kind. Trippur makes no warranty that (i) the service will meet your requirements, (ii) the service will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the service will be accurate or reliable, (iv) the quality of any products, services, information, or other material purchased or obtained by you through the service will meet your expectations, and (v) any errors in the service will be corrected. The information, software, and services on the website or in the app may include inaccuracies or typographical errors. In particular, Trippur and its affiliates do not guarantee the accuracy of, and disclaim liability for inaccuracies relating to the information and description of hotel, airline, and other travel products displayed on this website or app (including, without limitation, photographs, list of hotel amenities, general product descriptions, much of which information is provided by the respective suppliers. Hotel ratings displayed on this website or in the app are intended as only general guidelines, and Trippur and its affiliates do not guarantee the accuracy of the ratings. Trippur and/or its suppliers may make improvements and/or changes on this website or in the app at any time.</p>

    <p>Trippur makes no representations about the suitability of the information, product, and services contained on this website or in the app for any purpose, and the inclusion or offering for sale of any product or service on this website or in the app does not constitute an endorsement or recommendation of such products or services by Trippur. All such products and services are provided without warranty of any kind. Trippur, its affiliates, and/or their respective suppliers hereby disclaim all warranties and conditions with regard to this information, products, and services, including all implied warranties and conditions of merchantability, fitness for a particular purpose, title, and non-infringement.</p>

    <p>Trippur suppliers, including without limitation airlines, hotels, travel agencies and tour operators, providing travel or other services for or through Trippur are not agents or employees of Trippur. Trippur makes no warranties or guarantees with regard to the services provided by third party suppliers. Trippur is not liable for the acts, errors, omissions, representations, warranties, breaches, or negligence of any suppliers or for any personal injuries, death, property damage, or other damages or expenses resulting therefrom. Trippur has no liability and will make no refund in the event of any delay, cancellation, overbooking, strike, force majeure, or other causes beyond its direct control, and it has no responsibility for any additional expense, omission, delays, re-routing, or acts of any government or authority. In no event shall Trippur and its suppliers be liable for any direct, indirect, punitive, incidental, special, or consequential damages arising out of, or in any way connected with, the use of this website or app or with the delay or inability to use this website or app, or for any information, software, products, and services obtained through this website or app, or otherwise arising out of the use of this website or app. Notwithstanding the foregoing, in no event will the total, cumulative liability of Trippur (or its agents or suppliers) for damages under this agreement exceed the amounts earned by Trippur for the product or service giving rise to such damages.</p>

    <p className="title">Indemnification</p>
    <p>You agree to defend, indemnify and hold Trippur harmless from and against any claims, causes of action, demands, recoveries, losses, damages, fines, penalties, or other costs or expenses of any kind or nature including but not limited to legal and accounting fees, brought by (i) you or on your behalf in excess of the liability described above; or (ii) by third parties arising out of content you submit, post, transmit, or make available through the Trippur website or app, your use of the service, (iii) any third party arising out of your use of the service or the use of the service by any person using your profile and/or password, or (iv) by third parties arising out of your breach of these terms of use, or your violation of any law or the rights of a third party.</p>

    <p className="title">No unlawful or prohibited use</p>
    <p>As a condition of your use of this service, you warrant that you will not use the service for any purpose that is unlawful or prohibited by these terms, conditions, and notices. Trippur encourages you to use our Trip Share and Planning services as long as you follow the Trippur terms of use and Trippur 's prohibition of spamming and inappropriate content. In particular, it is prohibited to use Trippur 's computer systems to transmit unsolicited material except for the legitimate purpose of sharing trip itineraries. Violations of our Terms of service and spam policy may result in legal action against you and the termination, without notice, of your Trippur profile and all information and itineraries associated with it Trippur does not waive any rights by the failure to enforce this policy in every instance in which it might apply. You agree to not use the Trippur website or app to:</p>

    <ul>
        <li>Upload, post, email, or otherwise make available any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable;</li>
        <li>Impersonate any person or entity, including, but not limited to, a Trippur official or travel supplier, or to falsely state or otherwise misrepresent your affiliation with a person or entity;</li>
        <li>Upload, post, email, or otherwise make available any content that you do not have a right to make available;</li>
        <li>Upload, post, email, or otherwise make available any unsolicited or unauthorized advertising, promotional materials, "junk mail", "spam", or any other form of solicitation;</li>
        <li>Upload, post, email, or otherwise make available any material that contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
        <li>Interfere with or disrupt the Service or servers or networks connected to the Service.</li>
    </ul>

    <p>You acknowledge that Trippur may or may not screen content, but that Trippur has the right (but not the obligation) at its discretion to screen, refuse, or move any content that is available via the service. Without limiting the foregoing, Trippur and its designees shall have the right to remove any content that violates these terms of use or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness of such content. In this regard, you acknowledge that you may not rely on any content created by Trippur or submitted to Trippur.</p>
    Advertising and links to third-party sites
    <p>This website contains hyperlinks to web- or mobile sites operated by parties other than Trippur. Such hyperlinks are provided for your information and reference only. Trippur does not control such web- or mobile sites and is not responsible for their contents or your use of them. Trippur 's inclusion of hyperlinks to such web- or mobile sites does not imply any endorsement of the material on such web- or mobile sites or any association with their operators. You further acknowledge and agree that Trippur shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, goods or services available through any third party web- or mobile site.</p>

    <p className="title">Intellectual property</p>
    <p>You agree not to copy, reverse engineer, or attempt to discover any source code, distribute or create derivative works based on the service, in whole or in part. You agree not to access the service by any means other than through the interface that is provided by Trippur for use in accessing the service. In addition, any software that is made available from this website or app, including, without limitation, all HTML code and web controls, are owned by or licensed to Trippur. Any reproduction or redistribution of this software is expressly prohibited. Trippur 's travel searching, planning and purchasing tools are to assist users in determining the availability of travel-related goods and services. You warrant that you are at least 18 years of age and possess the legal authority to enter into this agreement and to use this website or app in accordance with all terms of use herein. You agree to be financially responsible for all of your use of this website or app (as well as for use of your profile by others, including, without limitation, minors living with you). You also warrant that all information supplied by you or members of your household in using this website and app is true and accurate. You understand all purchases on third party web- or mobile sites are made under the terms of use of the outlined on the suppliers web- or mobile site and that any violation of any supplier's conditions of purchase may result in cancellation of your reservation(s) or purchase, in your being denied access to any flights, hotels or car- or holiday rentals, in your forfeiting any monies paid for such reservation(s) or purchase. You shall be completely responsible for all charges, fees, duties, taxes, and assessments arising out of the use of this web- or mobile site.</p>

    <p className="title">Travel destinations</p>
    <p>Although most travel is completed without incident, travel to certain destinations may involve greater risk. By making travel available to particular destinations, Trippur does not represent or warrant that travel to such points is advisable or without risk and is not liable for damages or losses that may result from travel to such destinations.</p>

    <p className="title">Applicable Law</p>
    <p>Dutch law governs the terms of use of this agreement as well as any disputes that may arise from the agreement or using the Trippur website or app. Any legal actions that may arise will be filed in Amsterdam, The Netherlands, and the parties hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction of such courts over any suit, action or proceeding arising out of these terms of use.</p>
  </div>
)
